### PR TITLE
cockroachdb: add v23.1.13

### PR DESCRIPTION
**Pull request by Jolg42**
Release notes https://www.cockroachlabs.com/docs/releases/v23.1
It should appear once merged at https://hub.docker.com/r/prismagraphql/cockroachdb-custom/tags

I want to be able to test against a pinned version. I think it's a better approach.
Because our cockroachdb image for `23.1` was updated "recently" but it's not instantly obvious what's the exact version used.
The update resulted in Renovate picking up the new docker sha and with an automated PR
 https://github.com/prisma/prisma-engines/pull/4504 

I want to change the version in that PR for `23.1.13` once this PR is merged here.

### CODE REVIEW

**Review by Weakky — APPROVED** [review]
👍🏻

**Comment by Jolg42** [comment]
Note: I will merge this after the release

**Comment by Jolg42** [comment]
https://buildkite.com/prisma/prisma-engine-images/builds/319

**Comment by Jolg42** [comment]
Note: unrelated to this PR, cross compilation images failed with
https://buildkite.com/prisma/prisma-engine-images/builds/319#018cf368-7f16-4efd-930b-4480a1c978e4/6-9749
```
[2024-01-10T12:59:36Z] mv musl-1.2.3.tmp musl-1.2.3
 -     0:0- 0   -     0         0    : 000    0  0 0 -  : 0-02   :  ---0  :- 0 -:   - -   - 0 : 0       00 - :-  0   00     :0   0  2       0  -00 -:--  0:00:01 --:- -:----: - - : - -0  0:00:01 --:--:--     0
[2024-01-10T12:59:37Z] -    :   -  0-   :  -- -0-0:   - --  -: - :-  -   - 00:0 -:
[2024-01-10T12:59:37Z] --0- 0: :-00-:2:0 -0-- :-c 0:02u-: r-0:-l--0:-: : - (0- 72:)  -c  -u-0F-ra 
[2024-01-10T12:59:37Z] :l i-: l-  e :(d07- 
[2024-01-10T12:59:37Z] )-t  oF  a ci ol ne0nde
[2024-01-10T12:59:37Z]  ctto  cctuoorn lc:nfu e(tr7cpltm):   i(tFcro7au r)irf loltF:prea d(m.i7i glr)tenr odoFu  rcta..ooigo lnrnecngud oe. ncpottnor oetg roc ctto  np tfno4oer4 tct3f pt4t pm 4mt3iaoirf  rrtrafoeroftrtp.r eg.m2rgn3i nur2u.2r3.o2ro1gro4 . rmg pgnm ossupr:o.t rot Cr 4go44 u34pl 3o draantff' ttet:e 4 rrc 4C o2o23u33l n22ad4nfn2 m't sete rm:cc  sto2C: n 3oC2ntu1eoo ulcml sdts:dn e't rno'tCvt  oec suocelrnornvd
[2024-01-10T12:59:37Z] nenneer'cc
[2024-01-10T12:59:37Z] ttt   tctoo ons ensreevcretrv 
[2024-01-10T12:59:37Z] etr
[2024-01-10T12:59:37Z] o server
[2024-01-10T12:59:37Z] make: *** [Makefile:86: sources/mpfr-4.0.2.tar.bz2] Error 7
[2024-01-10T12:59:37Z] make: *** Waiting for unfinished jobs....
[2024-01-10T12:59:37Z] make: *** [Makefile:86: sources/gmp-6.1.2.tar.bz2] Error 7
[2024-01-10T12:59:37Z] make: *** [Makefile:86: sources/binutils-2.33.1.tar.xz] Error 7
[2024-01-10T12:59:37Z] make: *** [Makefile:86: sources/gcc-11.2.0.tar.xz] Error 7
[2024-01-10T12:59:37Z] make: *** [Makefile:86: sources/mpc-1.1.0.tar.gz] Error 7
[2024-01-10T12:59:37Z] The command '/bin/sh -c cd /tmp &&     git clone --depth 1 https://github.com/richfelker/musl-cross-make.git &&     cp /tmp/config.mak /tmp/musl-cross-make/config.mak &&     cd /tmp/musl-cross-make &&     export CFLAGS="-fPIC -g1" &&     export TARGET=aarch64-unknown-linux-musl &&     make -j$(nproc) && make install &&     cd /tmp && rm -rf /tmp/musl-cross-make' returned a non-zero code: 2
[2024-01-10T12:59:37Z] make: *** [build-linux-musl-arm-ssl-1.1.x] Error 2
[2024-01-10T12:59:37Z] 🚨 Error: The command exited with status 2
[2024-01-10T12:59:37Z] user command error: exit status 2
```

**Pull request merged**
